# -------------------------------------------
# A user-defined grammar for piping a few processors
# -------------------------------------------

<Processor>     := <CountDecimate> | <CumulativeSum> | <Mutator> | <QueueSource> ;
<CountDecimate> := Take one every <Number> from <Processor> ;
<CumulativeSum> := Accumulate <Processor> ;
<Mutator>       := Turn <Processor> into <Number> ;
<QueueSource>   := [ <Number> , <Number> , <Number> ] ;
<Number>        := ^[\\d]+;